// `.env.ts` is generated by the `npm run env` command

export const environment = {
  production: true,
  version: '1.0.0',
  appName: "fantahockey",
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
